services:
  openhiru:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "18790:18790" # Gateway
      - "3790:3790"   # WebChat
      - "3791:3791"   # Canvas
      - "3792:3792"   # Dashboard
    volumes:
      - openhiru_data:/root/.openhiru
    env_file:
      - .env

volumes:
  openhiru_data:
